### PR TITLE
adapt readme to reflect most current changes

### LINKED ISSUE #11: Adapt Readme to reflect most recent changes

### PR DESCRIPTION
**Pull request by Bartzi**
fixes #11

### CODE REVIEW

**Comment by sknebel** [comment]
technically not _included_ dependencies anymore -> I think it should be just called "dependencies".

**Comment by Bartzi** [comment]
good point... I will change that

**Comment by sknebel** [comment]
Oh, and what about Autobahn? It is not a direct frontend dependency, but at most a dependency of a dependency, right?

**Comment by Bartzi** [comment]
hmm yeah... somehow you are right. Its actually just a dependency of angular-wamp but I'm not sure whether we should get rid of it in the readme or not...

**Comment by sknebel** [comment]
On the other hand, we list it explicitely in the bower file for some reason, so it might be ok. IMHO both ways are fine: :+1:

**Comment by Bartzi** [comment]
alright I've changed `included dependencies` to `dependencies`

**Pull request merged**
