### PR TITLE
add AngularJS

### LINKED ISSUE #2: Create AngularJS base

### PR DESCRIPTION
**Pull request by Bartzi**
this PR adds Angular JS to our project, including a first view that shows a map and first websocket tests,
it also adds materializecss in order to make it easy to design a page with material design (which looks quite neat)
fixes #2

### CODE REVIEW

**Comment by sknebel** [comment]
This doesn't actually do anything with highway.js and we would use the Angular-WAMP stuff instead anyways, right? If yes, then I'd suggest to remove highway.js. Maybe even rebase this back to the beginning of time and make it a new clean master without the experiments (which we could keep on an archive-branch) in the history.

Also, I really would appreciate a link or two or a few pointers where to extend it to understand what's going on :)

**Comment by Bartzi** [comment]
yeah I think removing HighwayJS and putting it into an Angular module seems to be a good idea ;)

**Comment by Bartzi** [comment]
alright we now have an angular-wamp example page that shows how we could use websockets. I also added some links to the readme.md

**Comment by sknebel** [comment]
:+1:

**Pull request merged**
